// 'use client '
import Image from "next/image"
import Homebanner from "./components/home/Homebanner";
import HomeCollection from "./components/home/HomeCollection";
import HomeProduct from "./components/home/HomeProduct";
import HomeTranding from "./components/home/HomeTranding";
import HomeSeles from "./components/home/HomeSeles";
// import HomeOrder from "./components/home/HomeOrder";
import HomeCoustumer from "./components/home/HomeCoustumer";
import HomeNews from "./components/home/HomeNews";
import { bannerapi, categoryapi, homeFeaturedProduct, homeSellingapi, orderapi, productViewApi } from "../api-service/homeservice";

export const metadata = {
  title: "Home page",
  description: "Generated by create next app",
};


export default async function Home() {
  let bannerdata = await bannerapi()

  let productSels = await homeSellingapi()

  let showProduct = await productViewApi()
  console.log(showProduct);

  // let productDetails = await productApi()
  // console.log(productDetails);

  let categoryData = await categoryapi()
  console.log(categoryData);
  
  // console.log(categoryData[0]._id)

  // let homeOrder=await orderapi()

  let productData = await homeFeaturedProduct((categoryData[0]?._id))
  console.log("productData:", productData)
  return (
    <>
      <Homebanner bannerdata={bannerdata} />
      <HomeCollection />
      <HomeProduct categoryData={categoryData} productData={productData} showProduct={productData}/>
      <HomeSeles productSels={productSels} />
      {/* <HomeOrder  homeOrder={homeOrder}/> */}
      <HomeCoustumer />
      <HomeNews />


    </>

  );
  // slider work in already created file page.jsx
}

// import Image from "next/image";
// import HomeBanner from "./components/home/HomeBanner";
// import HomeCollection from "./components/home/HomeCollection";
// import HomeProducts from "./components/home/HomeProducts";
// import HomeNewTrendingCollections from "./components/home/HomeNewTrendingCollections";
// import HomeBestSellingProducts from "./components/home/HomeBestSellingProducts";
// import HomePolicy from "./components/home/HomePolicy";
// import HomeOurCustomerSay from "./components/home/HomeOurCustomerSay";
// import HomeNewsletter from "./components/home/HomeNewsletter";
// import { bannerApi, bestSellingProduct, categoryApi, homeCollectionApi, productApi } from "@/api-services/HomeServices";

// export default async function Home() {

//   let bannerData = await bannerApi()
//   let homeCollectionData = homeCollectionApi()
//   let categoryData = await categoryApi()
//   let productData = await productApi(categoryData[0]._id)
//   let bestSellingProductData = await bestSellingProduct()

//   return (
//     <>
//       <HomeBanner bannerData={bannerData} />
//       <HomeCollection homeCollectionData={homeCollectionData} />
//       <HomeProducts categoryData={categoryData} productData={productData} />
//       <HomeNewTrendingCollections />
//       <HomeBestSellingProducts bestSellingProductData={bestSellingProductData} />
//       <HomePolicy />
//       <HomeOurCustomerSay />
//       <HomeNewsletter />
//     </>
//   );
// }